# Generated by Django 5.2.3 on 2025-06-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_rating_rating_alter_restaurant_website"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.UniqueConstraint(
                fields=("name", "longitude", "latitude"), name="unique_named_location"
            ),
        ),
    ]
