# Generated by Django 5.2.3 on 2025-06-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_restaurant_unique_named_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("restaurants", models.ManyToManyField(to="base.restaurant")),
            ],
        ),
    ]
