# Generated by Django 5.2.3 on 2025-06-23 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_staff"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
