# Generated by Django 5.2.3 on 2025-06-23 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_delete_rating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sale",
        ),
    ]
